//! Molecular representation system
//!
//! This module provides the trait and types for molecular representations.

pub mod cartoon;
pub mod dot;
pub mod line;
pub mod mesh;
pub mod ribbon;
pub mod selection_indicator;
pub mod sphere;
pub mod stick;
pub mod surface;

use pymol_mol::{CoordSet, ObjectMolecule};
use pymol_settings::SettingResolver;

use crate::color_resolver::ColorResolver;

/// Types of molecular representations
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RepType {
    /// Lines connecting bonded atoms
    Lines,
    /// Van der Waals spheres
    Spheres,
    /// Cylinder sticks for bonds
    Sticks,
    /// Dot surface representation
    Dots,
    /// Triangle mesh surface
    Mesh,
    /// Molecular surface
    Surface,
    /// Cartoon representation
    Cartoon,
    /// Ribbon representation
    Ribbon,
    /// Non-bonded cross markers
    Nonbonded,
    /// Text labels
    Labels,
}

impl RepType {
    /// Get the RepMask bit for this representation type
    pub fn mask_bit(&self) -> u32 {
        use pymol_mol::RepMask;
        match self {
            RepType::Lines => RepMask::LINES,
            RepType::Spheres => RepMask::SPHERES,
            RepType::Sticks => RepMask::STICKS,
            RepType::Dots => RepMask::DOTS,
            RepType::Mesh => RepMask::MESH,
            RepType::Surface => RepMask::SURFACE,
            RepType::Cartoon => RepMask::CARTOON,
            RepType::Ribbon => RepMask::RIBBON,
            RepType::Nonbonded => RepMask::NONBONDED,
            RepType::Labels => RepMask::LABELS,
        }
    }
}

/// Trait for molecular representations
///
/// Representations generate GPU-renderable geometry from molecular data.
/// The typical lifecycle is:
/// 1. `build()` - Generate vertex data from molecular data
/// 2. `upload()` - Upload vertex data to GPU buffers
/// 3. `render()` - Record draw commands into a render pass
pub trait Representation {
    /// Generate vertex data from molecular data
    ///
    /// This method iterates over atoms/bonds and generates the vertex data
    /// needed for rendering. The data is stored internally until `upload()`.
    fn build(
        &mut self,
        molecule: &ObjectMolecule,
        coord_set: &CoordSet,
        colors: &ColorResolver,
        settings: &SettingResolver,
    );

    /// Upload vertex data to GPU buffers
    ///
    /// This transfers the vertex data generated by `build()` to GPU memory.
    fn upload(&mut self, device: &wgpu::Device, queue: &wgpu::Queue);

    /// Record render commands into a render pass
    ///
    /// This binds the pipeline and buffers, then issues draw calls.
    /// The pipeline must already be set up with the appropriate bind groups.
    fn render<'a>(&'a self, render_pass: &mut wgpu::RenderPass<'a>);

    /// Check if the representation needs to be rebuilt
    fn is_dirty(&self) -> bool;

    /// Mark the representation as needing a rebuild
    fn set_dirty(&mut self);

    /// Get the number of primitives (vertices, instances, etc.)
    fn primitive_count(&self) -> usize;

    /// Check if the representation has any geometry to render
    fn is_empty(&self) -> bool {
        self.primitive_count() == 0
    }
}
